version: '3.8'
services:
  mysql-db:
    image: mysql:8.0
    container_name: library-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: library_db
    ports:
      - "3307:3306"
  backend:
    build: ./library_backend
    ports:
      - "8080:8080"
    depends_on:
      - mysql-db
  frontend:
    build: ./library-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend